### ISSUE TITLE
Discord Bugs

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Scientia#264]
in the stone age the fire stick quest isnt triggering either its at 2 of 4 i made 2 fire stick and lit a block on fire  not sure what else i need to do
KeldariumI dag kl. 18:43
im not sure where exactly the quest line is messed up but in the stone age i have crafted  the fire sticks ,10 + barrels all of the artisn tools (wooden versions) 4 shelfs , 2cabinets,  and the wooden basin, also crafted campfire but wont let me place it bc i dont have fire stage.  im am also a skilled carpenter

KeldariumI dag kl. 18:51
i was able to get the knife party quest by crafting the basic worktable.
KeldariumI dag kl. 19:22
im now at 3 of 4 for the fire sticks  quest im not sure what the 4th requirment would be tho
i have unlocked the ore evcavate but still tells me shape mining is disabled when trying to use on ores. ive only tried  on coal and alum so far

**Comment by NillerMedDild** [comment]
alright got it so it seems  its the "tools of trade" quest then that is holding back the other advancements. i think it just needs to be changed to wooden tools to fix or any.  also ore excavate does work on coal but  i think the shape is set to something other than None  bc i had to set it to None  to get it to work and it will not allow you to use  shape function which i believe is
 intended.
Versed™I dag kl. 20:33
Quest Always Learning - doesnt seem to be triggering even though i have unlocked skilled carpenter
KeldariumI dag kl. 20:39
copper and alum ores are dulping when you break them
copper seems  to give you at least 4 when you break it and alum at least 2 idk so you can replace it over and over and keep getting more
Versed™I dag kl. 21:03
Found lead and silver  and novice mining level

**Comment by MaxNeedsSnacks** [comment]
Also a minor annoyance with pregenned crops is that they aren't spawned at 100% growth but because the dirt they're on has obviously gone dry they can't grow anymore, either.

This makes the wild plant achievement a pain to get.

**Comment by NillerMedDild** [comment]
Plants can grow on dry dirt though.

**Comment by MaxNeedsSnacks** [comment]
They can? I set randomTickSpeed to 300 and observed for a solid minute and nothing happened... weird

**Comment by NillerMedDild** [comment]
They're supposed to anyway. Guess I better set the advancement to check for the crop instead of harvesting it :(
