### ISSUE TITLE
Apprintence Tinker Quest

### ISSUE THREAD

**Issue by keldarium** [NillerMedDild/Scientia#266]
**Modpack version**
0.0.0e

**Can the issue be reproduced?**
Yes/no/unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Quest is not triggering when you have met all requirements. it seem to be stuck on the tomahawk,  shiv and defender quest. also can the requirement for the 10 artesian "flint tools" be  "any" tools

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
And you did complete the Tomahawk/Shiv/Defender quests?

**Comment by NillerMedDild** [comment]
I forgot " here as well iirc
