### ISSUE TITLE
Stone Age Advancements

### ISSUE THREAD

**Issue by keldarium** [NillerMedDild/Scientia#268]
**Modpack version**
0.0.0e

**Can the issue be reproduced?**
Yes

**Issue**
here is a summary for stone age - 
"tools of trade" needs to change tool type from stone to something obtainable 
"Always learning " doesn't trigger due to "skilled carpenter"
"Bucket of Balance " doesn't trigger due to "feuer frei"
"Leather Working 2 " doesn't trigger due to "Salty"
"Diggy Diggy Hole " doesn't trigger due to "Novice Miner "
"Basic Fertilizer " doesn't trigger due to" Agri Expansion 1"

**Comment by NillerMedDild** [comment]
You completed the required advancements, and they didn't trigger?

For example, you completed Feuer Frei but Bucket of Balance was still not completeable?

**Comment by NillerMedDild** [comment]
I see I forgot " a few places, should be fixed now :)
