### ISSUE TITLE
Wild Crop Advancement

### ISSUE THREAD

**Issue by keldarium** [NillerMedDild/Scientia#270]
**Modpack version**
0.0.0g

**Can the issue be reproduced?**
Yes
**Issue**
The "wild crop" advancement in the "dawn of time" age is being triggered by acorns.

**Comment by NillerMedDild** [comment]
Hmm I probably misspelt something ^^'

**Comment by NillerMedDild** [comment]
I sure did, thanks for the report, I really appreciate your help.
