### ISSUE TITLE
Cobblestone Recipe Missing

### ISSUE THREAD

**Issue by keldarium** [NillerMedDild/Scientia#271]
**Modpack version
0.0.0g
**Can the issue be reproduced?**
Yes

**Issue**
Cobblestone recipe is missing.

If this is a feature request, feel free to delete the template.

**Comment by Dimentive** [comment]
What recipe are you referring to, exactly?

You can’t craft cobblestone in vanilla (unmodded) Minecraft.

**Comment by keldarium** [comment]
I don't for sure know if the recipe is missing or if I'm just not seeing to due to it being locked behind the stone age. but in 0.0.0f it is uncraftable as well. so that lead me to believe the recipe is missing.

**Comment by NillerMedDild** [comment]
It should be locked behind the stone age, but I'll double check :)
