### ISSUE TITLE
Stone Age Advancement

### ISSUE THREAD

**Issue by keldarium** [NillerMedDild/Scientia#272]
**Modpack version**
0.0.0h
**Can the issue be reproduced?**
Yes

**Issue**
The "Internship" advancement is NOT triggering when right clicking book.
The "Tinkering", "Agricultural expansion" and "Seasons" ARE triggered without right clicking appropriate books

**Comment by NillerMedDild** [comment]
Most of those are intentional, I've updated the descriptions to better reflect what you have to do :)
