### ISSUE TITLE
Stone Age Advancement "Salty"

### ISSUE THREAD

**Issue by keldarium** [NillerMedDild/Scientia#283]
**Modpack version**
Master

**Issue**
Salty is Broken. Missing Salt trigger

**Comment by keldarium** [comment]
Interesting Salty Just triggered about a 15min delay though and I had 40 salt the whole time in my inventory.

**Comment by NillerMedDild** [comment]
That is super weird, I'll try to replicate it. Sorry about all the bugs, it seems all the advancements are broken.

**Comment by keldarium** [comment]
I believe you had mentioned that they reverted back after an update. Its all good that's what signed up for.

**Comment by NillerMedDild** [comment]
It's not detecting the amount correctly for some reason, changed to 1 salt.

**Comment by NillerMedDild** [comment]
Yep, that revert messed up about 30 advancements :P
