### ISSUE TITLE
Stone Age Advancement "Always Learning"

### ISSUE THREAD

**Issue by keldarium** [NillerMedDild/Scientia#292]
**Modpack version**
Master 

**Issue**
The Always learning Advancement is still not working. Skilled Carpenter trigger is missing. 

Something I did notice I'm not sure it has anything to do with this but the skilled carpenter triggers with just 1 of the required items not the amount that it is asking for. IE:  It asks for 3drying racks but 1 drying rack will complete it.

**Comment by NillerMedDild** [comment]
I'm a derp, typo in the advancement requirement ^^'
