### ISSUE TITLE
Zombie Event in Dawn of Time Age

### ISSUE THREAD

**Issue by keldarium** [NillerMedDild/Scientia#293]
**Modpack version**
Master
**Can the issue be reproduced?**
unknown

**Issue**
 I Had a weird event at a village I was at for many nights. In the dawn of time age  I had a zombie hoard spawn and take out most of the villagers. I think this might be a vanilla rare occurrence hence the reason I'm calling it an event. also in my playing I have seen a zombie village as well in the dawn of time age. I know this is defiantly a vanilla mechanic.

**Comment by NillerMedDild** [comment]
That was most likely caused by the mod BrutalZombieRaid mod, I removed it and will try to implement something more controlled, so it doesn't happen in the Dawn of Time :)
