### ISSUE TITLE
Tannin Recipe No work

### ISSUE THREAD

**Issue by keldarium** [NillerMedDild/Scientia#296]
**Modpack version**
Master

**Can the issue be reproduced?**
Yes

**Issue**
The Tannin Recipe  is broken on the anvil

**Comment by NillerMedDild** [comment]
I've been looking into this issue, not sure what the cause is yet. Primal Tech CraftTweaker integration is a bit odd.

**Comment by NillerMedDild** [comment]
Fixed! It was unhappy about me not specifying metadata.
